---
- hosts: controller
  tasks:
    - name: Create inventory file
      template:
        src: inventory.j2
        dest: ~/inventory
        mode: 0644

    - name: Setup base test_options
      set_fact:
        _test_options: "--continue-on-error --diff --tox "

    - name: Enable --tox-sitepackages for test_options
      set_fact:
        _test_options: "{{ _test_options }} --tox-sitepackages "
      when: ansible_os_family == "RedHat"

    - name: Run the integration test suite
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
      shell: "./test/runner/ansible-test network-integration {{ _test_options }} --python {{ ansible_test_python }} --inventory /home/zuul/inventory vyos_.* -vv"
