---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-test-network-integration-junos-python36
    gate:
      jobs:
        - ansible-network-eos-appliance
        - ansible-network-junos-appliance
        - ansible-network-vyos-appliance
