---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-test-network-integration-vyos-python27
        - ansible-test-network-integration-vyos-python36
        - ansible-test-network-integration-vyos-python37
    gate:
      jobs:
        - ansible-network-eos-appliance
        - ansible-network-vyos-appliance
