---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-test-network-integration-eos-python35
        - ansible-test-network-integration-vyos-python35
    gate:
      jobs:
        - ansible-network-eos-appliance
        - ansible-network-vyos-appliance
