---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-test-network-integration-openvswitch-python27
        - ansible-test-network-integration-openvswitch-python35
        - ansible-test-network-integration-openvswitch-python36
        - ansible-test-network-integration-openvswitch-python37
