---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-cloud-vcsa-appliance
        - ansible-network-eos-appliance
        - ansible-network-ios-appliance
        - ansible-network-iosxr-appliance
        - ansible-network-junos-appliance
        - ansible-network-openvswitch-appliance
        - ansible-network-vyos-appliance
    gate:
      jobs:
        - ansible-cloud-vcsa-appliance
        - ansible-network-eos-appliance
        - ansible-network-ios-appliance
        - ansible-network-iosxr-appliance
        - ansible-network-junos-appliance
        - ansible-network-openvswitch-appliance
        - ansible-network-vyos-appliance
