---
- hosts: all
  tasks:
    - name: Setup base virtualenv_options
      set_fact:
        _virtualenv_options: "--python python{{ ansible_test_python }}"

    - name: Enable --system-site-packages for virtualenv_options
      set_fact:
        _virtualenv_options: "{{ _virtualenv_options }} --system-site-packages"
      when: ansible_os_family == "RedHat"

    - name: Create virtualenv for ansible-test
      shell: "virtualenv {{ _virtualenv_options }} ~/venv"

    - name: Install ara into virtuelenv
      shell: ~/venv/bin/pip install "ara<1.0.0"

    - name: Enable ARA callback plugin
      ini_file:
        path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/test/integration/network-integration.cfg"
        section: defaults
        option: callback_plugins
        value: "{{ ansible_user_dir }}/venv/lib/python{{ ansible_test_python}}/site-packages/ara/plugins/callbacks"

    - name: Setup base test_options
      set_fact:
        _test_options: "--requirements --python {{ ansible_test_python }}"

    - name: Run the sanity test suite
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
        executable: /bin/bash
      shell: "source ~/venv/bin/activate; ./test/runner/ansible-test sanity {{ _test_options }}"
