---
- hosts: all
  tasks:
    - name: Install docker
      include_role:
        name: ensure-docker

    - name: Run buildset registry (if not already running)
      when: buildset_registry is not defined
      include_role:
        name: run-buildset-registry

    - name: Use buildset registry
      include_role:
        name: use-buildset-registry
