---
- hosts: all
  tasks:
    - name: Install container runtime
      include_role:
        name: "ensure-{{ (container_command == 'docker') | ternary('docker', 'podman') }}"

    - name: Setup buildset registry (if not already running)
      block:
        # NOTE(pabelanger): we force docker until we can figure out podman IPV6 issue
        - name: Install docker runtime
          include_role:
            name: ensure-docker

        - name: Run buildset registry
          include_role:
            name: run-buildset-registry
          vars:
            container_command: docker
      when: buildset_registry is not defined

    - name: Use buildset registry
      include_role:
        name: use-buildset-registry
